import { ScholarshipApplication, ScholarshipScheme, PfmsBatch, PfmsFailure, GrievanceTicket } from '../types';

export const INITIAL_SCHEMES: ScholarshipScheme[] = [
  {
    id: 'SCH-NFST-01',
    code: 'NFST-2026',
    name: 'National Fellowship for ST (NFST)',
    category: 'Higher Education / Ph.D',
    academicYear: '2026 - 2027',
    sanctionCap: 750,
    annualBudget: '₹ 180.00 Cr',
    totalApplied: 48200,
    verifiedCount: 41200,
    pendingCount: 6100,
    defectiveCount: 900,
    portalOpeningDate: '2026-06-01',
    inoDeadline: '2026-09-30',
    dnoDeadline: '2026-10-31',
    rules: [
      { id: 'r1', parameter: 'Caste Category', operator: 'EQUALS', value: 'Scheduled Tribe (ST)', status: 'Strict Pass' },
      { id: 'r2', parameter: 'Family Annual Income', operator: 'LESS_THAN_OR_EQUAL', value: '600000', status: 'Strict Pass' },
      { id: 'r3', parameter: 'Aadhaar NPCI Status', operator: 'EQUALS', value: 'ACTIVE_NPCI_SEEDED', status: 'Strict Pass' },
      { id: 'r4', parameter: 'Postgraduate Score (%)', operator: 'GREATER_THAN_OR_EQUAL', value: '55', status: 'Strict Pass' },
    ],
    mandatoryDocuments: {
      aadhaar: true,
      casteCert: true,
      incomeCert: true,
      degreeMarksheet: true,
      bankPassbook: true,
      bonafideCert: true,
      phdRegistration: true,
    }
  },
  {
    id: 'SCH-NOS-02',
    code: 'NOS-ST-2026',
    name: 'National Overseas Scholarship for ST',
    category: 'International Education',
    academicYear: '2026 - 2027',
    sanctionCap: 120,
    annualBudget: '₹ 45.00 Cr',
    totalApplied: 3200,
    verifiedCount: 2600,
    pendingCount: 450,
    defectiveCount: 150,
    portalOpeningDate: '2026-05-15',
    inoDeadline: '2026-09-15',
    dnoDeadline: '2026-10-15',
    rules: [
      { id: 'r10', parameter: 'Caste Category', operator: 'EQUALS', value: 'Scheduled Tribe (ST)', status: 'Strict Pass' },
      { id: 'r11', parameter: 'Family Annual Income', operator: 'LESS_THAN_OR_EQUAL', value: '600000', status: 'Strict Pass' },
      { id: 'r12', parameter: 'University World Ranking (QS)', operator: 'LESS_THAN_OR_EQUAL', value: '500', status: 'Strict Pass' },
    ],
    mandatoryDocuments: {
      aadhaar: true,
      casteCert: true,
      incomeCert: true,
      degreeMarksheet: true,
      bankPassbook: true,
      bonafideCert: true,
    }
  },
  {
    id: 'SCH-PMSC-03',
    code: 'POST-MATRIC-ST',
    name: 'Post-Matric Scholarship for ST Students',
    category: 'Post-Secondary (XI to UG/PG)',
    academicYear: '2026 - 2027',
    sanctionCap: 150000,
    annualBudget: '₹ 850.00 Cr',
    totalApplied: 142000,
    verifiedCount: 118000,
    pendingCount: 21000,
    defectiveCount: 3000,
    portalOpeningDate: '2026-07-01',
    inoDeadline: '2026-10-15',
    dnoDeadline: '2026-11-15',
    rules: [
      { id: 'r20', parameter: 'Caste Category', operator: 'EQUALS', value: 'Scheduled Tribe (ST)', status: 'Strict Pass' },
      { id: 'r21', parameter: 'Family Annual Income', operator: 'LESS_THAN_OR_EQUAL', value: '250000', status: 'Strict Pass' },
    ],
    mandatoryDocuments: {
      aadhaar: true,
      casteCert: true,
      incomeCert: true,
      degreeMarksheet: true,
      bankPassbook: true,
      bonafideCert: true,
    }
  },
  {
    id: 'SCH-PREM-04',
    code: 'PRE-MATRIC-ST',
    name: 'Pre-Matric Scholarship for ST (Class IX & X)',
    category: 'Secondary Education',
    academicYear: '2026 - 2027',
    sanctionCap: 200000,
    annualBudget: '₹ 400.00 Cr',
    totalApplied: 185000,
    verifiedCount: 165000,
    pendingCount: 16000,
    defectiveCount: 4000,
    portalOpeningDate: '2026-07-01',
    inoDeadline: '2026-10-01',
    dnoDeadline: '2026-10-31',
    rules: [
      { id: 'r30', parameter: 'Caste Category', operator: 'EQUALS', value: 'Scheduled Tribe (ST)', status: 'Strict Pass' },
      { id: 'r31', parameter: 'Family Annual Income', operator: 'LESS_THAN_OR_EQUAL', value: '250000', status: 'Strict Pass' },
    ],
    mandatoryDocuments: {
      aadhaar: true,
      casteCert: true,
      incomeCert: true,
      degreeMarksheet: true,
      bankPassbook: true,
      bonafideCert: true,
    }
  }
];

export const INITIAL_APPLICATIONS: ScholarshipApplication[] = [
  {
    id: 'IND-ST-2026-992',
    applicantName: 'Sita Munda',
    fatherName: 'Birsa Munda',
    dob: '2002-05-12',
    gender: 'Female',
    tribe: 'Munda',
    state: 'Jharkhand',
    district: 'Ranchi',
    institution: 'Birla Institute of Technology (BIT Mesra)',
    schemeId: 'SCH-NOS-02',
    schemeName: 'National Overseas Scholarship for ST',
    annualIncomeDeclared: 120000,
    annualIncomeExtracted: 220000,
    incomeMismatch: true,
    casteCertNo: 'JH/RNC/ST/2024/77189',
    casteVerified: true,
    aadhaarSeeded: true,
    bankAccount: '38920194821',
    bankIfsc: 'SBIN0000691',
    bankName: 'State Bank of India (Main Branch Ranchi)',
    aiConfidenceScore: 48,
    status: 'FLAGGED',
    discrepancySignal: 'Income mismatch: Extracted ₹2,20,000 vs Declared ₹1,20,000',
    triageFolder: 'flagged',
    appliedDate: '2026-08-14',
    ocrConflictNote: 'AI OCR conflict: High confidence 99.2% match with "₹ 2,20,000/-" on Tehsildar stamped Income Certificate.',
    defectRemarks: 'Income mismatch: Stamped Certificate shows ₹2,20,000 while portal declaration is ₹1,20,000.',
    documentList: [
      { 
        id: 'doc-1', 
        name: 'Income_Cert_SitaMunda_Signed.pdf', 
        hasDiscrepancy: true, 
        statusBadge: '⚠️ Discrepancy Flagged', 
        type: 'INCOME',
        certNumber: 'RNC/INC/2026/09941',
        issueDate: '14/02/2026',
        issuingAuthority: 'Office of Sub-Divisional Magistrate, Ranchi',
        extractedIncome: 220000,
        qrHash: 'JH-SDM-RNC-9941-VERIFIED',
        discrepancyNote: 'Conflict detected: Declared ₹1,20,000 vs Certificate Value ₹2,20,000'
      },
      { 
        id: 'doc-2', 
        name: 'Caste_Certificate_ST_Ranchi.pdf', 
        hasDiscrepancy: false, 
        statusBadge: '✅ Verified e-District', 
        type: 'CASTE',
        certNumber: 'JH/RNC/ST/2024/77189',
        issueDate: '10/01/2024',
        issuingAuthority: 'Sub-Divisional Officer (Sadar Ranchi)',
        extractedTribe: 'Munda (Scheduled Tribe)'
      },
      { 
        id: 'doc-3', 
        name: 'Aadhaar_Offline_eKYC_XML.pdf', 
        hasDiscrepancy: false, 
        statusBadge: '✅ Biometric Match', 
        type: 'AADHAAR',
        extractedAadhaarMask: 'XXXXXXXX4821',
        issuingAuthority: 'UIDAI Aadhaar Data Vault'
      },
      { 
        id: 'doc-4', 
        name: 'Bonafide_Student_Certificate_BIT.pdf', 
        hasDiscrepancy: false, 
        statusBadge: '✅ INO Endorsed', 
        type: 'BONAFIDE',
        extractedCollege: 'Birla Institute of Technology (BIT Mesra), Ranchi',
        issuingAuthority: 'Dean of Academic Affairs, BIT Mesra'
      },
      { 
        id: 'doc-5', 
        name: 'Bank_Passbook_NPCI_Seeded.pdf', 
        hasDiscrepancy: false, 
        statusBadge: '✅ Account Active', 
        type: 'BANK',
        extractedBank: 'State Bank of India (Main Branch Ranchi)',
        extractedIfsc: 'SBIN0000691'
      }
    ]
  },
  {
    id: 'IND-ST-2026-8819',
    applicantName: 'Rajesh Meena',
    fatherName: 'Ramprasad Meena',
    dob: '2001-08-24',
    gender: 'Male',
    tribe: 'Meena',
    state: 'Rajasthan',
    district: 'Udaipur',
    institution: 'Mohanlal Sukhadia University',
    schemeId: 'SCH-NFST-01',
    schemeName: 'National Fellowship for ST (NFST)',
    annualIncomeDeclared: 180000,
    annualIncomeExtracted: 180000,
    incomeMismatch: false,
    casteCertNo: 'RJ/UDP/ST/2025/11029',
    casteVerified: true,
    aadhaarSeeded: true,
    bankAccount: '20491004821',
    bankIfsc: 'BARB0UDAIPU',
    bankName: 'Bank of Baroda (Udaipur City)',
    aiConfidenceScore: 98,
    status: 'AUTO_VERIFIED',
    discrepancySignal: 'All documents hashed & e-District verified',
    triageFolder: 'high',
    appliedDate: '2026-08-10',
    documentList: [
      { 
        id: 'doc-10', 
        name: 'Income_Cert_RajeshMeena.pdf', 
        hasDiscrepancy: false, 
        statusBadge: '✅ e-District Validated', 
        type: 'INCOME',
        certNumber: 'RJ/UDP/INC/2026/88190',
        issueDate: '05/03/2026',
        issuingAuthority: 'Tehsildar Office, Girwa, Udaipur',
        extractedIncome: 180000,
        qrHash: 'RJ-E-DISTRICT-UDP-8819'
      },
      { 
        id: 'doc-11', 
        name: 'Caste_Certificate_Meena.pdf', 
        hasDiscrepancy: false, 
        statusBadge: '✅ Rajasthan Portal Synced', 
        type: 'CASTE',
        certNumber: 'RJ/UDP/ST/2025/11029',
        issueDate: '12/04/2025',
        issuingAuthority: 'Sub-Divisional Magistrate, Udaipur',
        extractedTribe: 'Meena (ST Rajasthan)'
      },
      { 
        id: 'doc-12', 
        name: 'Aadhaar_eKYC.pdf', 
        hasDiscrepancy: false, 
        statusBadge: '✅ Verified', 
        type: 'AADHAAR',
        extractedAadhaarMask: 'XXXXXXXX1102',
        issuingAuthority: 'UIDAI Vault'
      }
    ]
  },
  {
    id: 'IND-ST-2026-8902',
    applicantName: 'Anjali Bhil',
    fatherName: 'Kalu Singh Bhil',
    dob: '2003-02-18',
    gender: 'Female',
    tribe: 'Bhil',
    state: 'Madhya Pradesh',
    district: 'Jhabua',
    institution: 'Govt Post Graduate College Jhabua',
    schemeId: 'SCH-PMSC-03',
    schemeName: 'Post-Matric Scholarship for ST Students',
    annualIncomeDeclared: 95000,
    annualIncomeExtracted: 95000,
    incomeMismatch: false,
    casteCertNo: 'MP/JHB/ST/2024/99104',
    casteVerified: true,
    aadhaarSeeded: true,
    bankAccount: '55102948192',
    bankIfsc: 'SBIN0001822',
    bankName: 'State Bank of India (Jhabua)',
    aiConfidenceScore: 96,
    status: 'AUTO_VERIFIED',
    discrepancySignal: 'Samagra Portal Caste UID verified',
    triageFolder: 'high',
    appliedDate: '2026-08-12',
    documentList: [
      { 
        id: 'doc-20', 
        name: 'Samagra_Income_AnjaliBhil.pdf', 
        hasDiscrepancy: false, 
        statusBadge: '✅ Samagra MP Verified', 
        type: 'INCOME',
        certNumber: 'MP/SAMAGRA/INC/2026/00912',
        issueDate: '18/01/2026',
        issuingAuthority: 'Revenue Officer, Jhabua Block',
        extractedIncome: 95000,
        qrHash: 'MP-SAMAGRA-99104'
      },
      { 
        id: 'doc-21', 
        name: 'ST_Caste_Jhabua.pdf', 
        hasDiscrepancy: false, 
        statusBadge: '✅ Verified', 
        type: 'CASTE',
        certNumber: 'MP/JHB/ST/2024/99104',
        issueDate: '14/08/2024',
        issuingAuthority: 'SDM Jhabua',
        extractedTribe: 'Bhil (Scheduled Tribe MP)'
      }
    ]
  },
  {
    id: 'IND-ST-2026-9114',
    applicantName: 'Ramesh Oraon',
    fatherName: 'Sukhu Oraon',
    dob: '2000-11-05',
    gender: 'Male',
    tribe: 'Oraon',
    state: 'Chhattisgarh',
    district: 'Bastar',
    institution: 'Bastar Vishwavidyalaya Jagdalpur',
    schemeId: 'SCH-NFST-01',
    schemeName: 'National Fellowship for ST (NFST)',
    annualIncomeDeclared: 150000,
    annualIncomeExtracted: 150000,
    incomeMismatch: false,
    casteCertNo: 'CG/BST/ST/2024/44012',
    casteVerified: true,
    aadhaarSeeded: true,
    bankAccount: '30491029481',
    bankIfsc: 'CNRB0002104',
    bankName: 'Canara Bank (Jagdalpur)',
    aiConfidenceScore: 99,
    status: 'AUTO_VERIFIED',
    discrepancySignal: 'Income verified under ₹2 Lakh',
    triageFolder: 'high',
    appliedDate: '2026-08-01',
    documentList: [
      { 
        id: 'doc-30', 
        name: 'Income_Certificate_Oraon.pdf', 
        hasDiscrepancy: false, 
        statusBadge: '✅ e-Pramaan Verified', 
        type: 'INCOME',
        certNumber: 'CG/BST/INC/2026/33109',
        issueDate: '20/02/2026',
        issuingAuthority: 'Tehsildar Jagdalpur, Bastar',
        extractedIncome: 150000,
        qrHash: 'CG-EDISTRICT-BST-33109'
      }
    ]
  },
  {
    id: 'IND-ST-2026-9450',
    applicantName: 'Priya Meena',
    fatherName: 'Deviram Meena',
    dob: '2004-09-30',
    gender: 'Female',
    tribe: 'Meena',
    state: 'Rajasthan',
    district: 'Dungarpur',
    institution: 'Govt College Dungarpur',
    schemeId: 'SCH-PREM-04',
    schemeName: 'Pre-Matric ST Scholarship',
    annualIncomeDeclared: 110000,
    annualIncomeExtracted: 140000,
    incomeMismatch: false,
    casteCertNo: 'RJ/DNG/ST/2025/30912',
    casteVerified: true,
    aadhaarSeeded: false,
    bankAccount: '11029384910',
    bankIfsc: 'PUNB0109200',
    bankName: 'Punjab National Bank (Dungarpur)',
    aiConfidenceScore: 74,
    status: 'NEEDS_REVIEW',
    discrepancySignal: 'Handwritten revenue seal on Income Cert - NPCI seeding pending',
    triageFolder: 'manual',
    appliedDate: '2026-08-18',
    ocrConflictNote: 'AI Note: Revenue seal is blurred. Income verified manually by Tehsildar physically.',
    documentList: [
      { 
        id: 'doc-40', 
        name: 'Income_Cert_Handwritten_Stamp.pdf', 
        hasDiscrepancy: true, 
        statusBadge: '🟡 Manual Stamp Review', 
        type: 'INCOME',
        certNumber: 'RJ/DNG/INC/2026/0019',
        issueDate: '12/03/2026',
        issuingAuthority: 'Naib Tehsildar, Aspur, Dungarpur',
        extractedIncome: 140000,
        discrepancyNote: 'Blurred seal. Requires DNO visual sign-off.'
      }
    ]
  },
  {
    id: 'IND-ST-2026-9502',
    applicantName: 'Sanjay Tirkey',
    fatherName: 'Bandhu Tirkey',
    dob: '2001-04-14',
    gender: 'Male',
    tribe: 'Oraon',
    state: 'Odisha',
    district: 'Sundargarh',
    institution: 'National Institute of Technology Rourkela',
    schemeId: 'SCH-PMSC-03',
    schemeName: 'Post-Matric Scholarship for ST Students',
    annualIncomeDeclared: 160000,
    annualIncomeExtracted: 160000,
    incomeMismatch: false,
    casteCertNo: 'OD/SNG/ST/2025/88120',
    casteVerified: true,
    aadhaarSeeded: true,
    bankAccount: '40192830192',
    bankIfsc: 'SBIN0002109',
    bankName: 'State Bank of India (NIT Rourkela)',
    aiConfidenceScore: 82,
    status: 'NEEDS_REVIEW',
    discrepancySignal: 'Minor spelling variation in father name (Bandhu vs Bandho)',
    triageFolder: 'manual',
    appliedDate: '2026-08-20',
    documentList: [
      { 
        id: 'doc-50', 
        name: 'Caste_Cert_Odisha.pdf', 
        hasDiscrepancy: true, 
        statusBadge: '🟡 Name Fuzzy Match (91%)', 
        type: 'CASTE',
        certNumber: 'OD/SNG/ST/2025/88120',
        issueDate: '09/05/2025',
        issuingAuthority: 'Tahasildar, Panposh, Sundargarh',
        extractedTribe: 'Oraon (ST Odisha)',
        discrepancyNote: 'Father name on Caste Certificate spelled "Bandho Tirkey"'
      }
    ]
  },
  {
    id: 'IND-ST-2026-998',
    applicantName: 'Sunil Netam',
    fatherName: 'Jagdish Netam',
    dob: '1999-12-01',
    gender: 'Male',
    tribe: 'Gond',
    state: 'Chhattisgarh',
    district: 'Bastar',
    institution: 'Government Kakatiya PG College Jagdalpur',
    schemeId: 'SCH-NFST-01',
    schemeName: 'National Fellowship for ST (NFST)',
    annualIncomeDeclared: 80000,
    annualIncomeExtracted: 450000,
    incomeMismatch: true,
    casteCertNo: 'CG/BST/ST/2023/00192',
    casteVerified: false,
    aadhaarSeeded: false,
    bankAccount: '99102938410',
    bankIfsc: 'UTBI0908123',
    bankName: 'United Bank of India',
    aiConfidenceScore: 22,
    status: 'REJECTED',
    discrepancySignal: 'Duplicate Income Cert Hash across 4 applicants & False declaration',
    triageFolder: 'flagged',
    appliedDate: '2026-08-22',
    rejectionReason: 'Fraudulent Document Hash: Certificate hash matches 4 other applications in Bastar district.',
    documentList: [
      { 
        id: 'doc-60', 
        name: 'Income_Cert_Duplicate_Hash.pdf', 
        hasDiscrepancy: true, 
        statusBadge: '🔴 Fraudulent Hash Signal', 
        type: 'INCOME',
        certNumber: 'CG/BST/INC/DUPLICATE-77',
        issueDate: '01/01/2026',
        issuingAuthority: 'Forged Stamp Signal',
        extractedIncome: 450000,
        discrepancyNote: 'SHA-256 hash collision with 4 other student dockets in Bastar.'
      }
    ]
  },
  {
    id: 'IND-ST-2026-9610',
    applicantName: 'Kavita Marandi',
    fatherName: 'Hopna Marandi',
    dob: '2003-07-19',
    gender: 'Female',
    tribe: 'Santhal',
    state: 'Jharkhand',
    district: 'Dumka',
    institution: 'Sido Kanhu Murmu University',
    schemeId: 'SCH-PMSC-03',
    schemeName: 'Post-Matric Scholarship for ST Students',
    annualIncomeDeclared: 140000,
    annualIncomeExtracted: 140000,
    incomeMismatch: false,
    casteCertNo: 'JH/DMK/ST/2025/55102',
    casteVerified: true,
    aadhaarSeeded: true,
    bankAccount: '20938491029',
    bankIfsc: 'SBIN0000881',
    bankName: 'State Bank of India (Dumka Branch)',
    aiConfidenceScore: 97,
    status: 'AUTO_VERIFIED',
    discrepancySignal: 'JharSewa Digital Token Validated',
    triageFolder: 'high',
    appliedDate: '2026-08-05',
    documentList: [
      { 
        id: 'doc-70', 
        name: 'Income_Dumka_JharSewa.pdf', 
        hasDiscrepancy: false, 
        statusBadge: '✅ JharSewa Synced', 
        type: 'INCOME',
        certNumber: 'JH/DMK/INC/2026/55102',
        issueDate: '10/02/2026',
        issuingAuthority: 'Circle Officer, Dumka Sadar',
        extractedIncome: 140000,
        qrHash: 'JH-JHARSEWA-DMK-55102'
      }
    ]
  },
  {
    id: 'IND-ST-2026-9622',
    applicantName: 'Amit Bhil',
    fatherName: 'Mangilal Bhil',
    dob: '2004-12-10',
    gender: 'Male',
    tribe: 'Bhil',
    state: 'Madhya Pradesh',
    district: 'Dhar',
    institution: 'Govt Boys H.S. School Dhar',
    schemeId: 'SCH-PREM-04',
    schemeName: 'Pre-Matric ST Scholarship',
    annualIncomeDeclared: 85000,
    annualIncomeExtracted: 85000,
    incomeMismatch: false,
    casteCertNo: 'MP/DHR/ST/2024/22091',
    casteVerified: true,
    aadhaarSeeded: true,
    bankAccount: '11092837491',
    bankIfsc: 'PUNB0291800',
    bankName: 'Punjab National Bank (Dhar)',
    aiConfidenceScore: 95,
    status: 'AUTO_VERIFIED',
    discrepancySignal: 'MP e-District & Samagra Verified',
    triageFolder: 'high',
    appliedDate: '2026-08-11',
    documentList: [
      { 
        id: 'doc-80', 
        name: 'Samagra_Income_Dhar.pdf', 
        hasDiscrepancy: false, 
        statusBadge: '✅ Verified', 
        type: 'INCOME',
        certNumber: 'MP/DHR/INC/2026/22091',
        issueDate: '15/01/2026',
        issuingAuthority: 'Tehsildar Dhar',
        extractedIncome: 85000
      }
    ]
  },
  {
    id: 'IND-ST-2026-9640',
    applicantName: 'Sunita Khadia',
    fatherName: 'Dharma Khadia',
    dob: '2001-09-02',
    gender: 'Female',
    tribe: 'Khadia',
    state: 'Odisha',
    district: 'Mayurbhanj',
    institution: 'North Orissa University Baripada',
    schemeId: 'SCH-NFST-01',
    schemeName: 'National Fellowship for ST (NFST)',
    annualIncomeDeclared: 210000,
    annualIncomeExtracted: 210000,
    incomeMismatch: false,
    casteCertNo: 'OD/MBJ/ST/2025/00912',
    casteVerified: true,
    aadhaarSeeded: false,
    bankAccount: '30928102938',
    bankIfsc: 'UCBA0001092',
    bankName: 'UCO Bank (Baripada)',
    aiConfidenceScore: 68,
    status: 'NEEDS_REVIEW',
    discrepancySignal: 'Aadhaar seeding unverified at NPCI mapper',
    triageFolder: 'manual',
    appliedDate: '2026-08-15',
    documentList: [
      { 
        id: 'doc-90', 
        name: 'Income_Mayurbhanj.pdf', 
        hasDiscrepancy: false, 
        statusBadge: '✅ Valid', 
        type: 'INCOME',
        certNumber: 'OD/MBJ/INC/2026/00912',
        issueDate: '25/02/2026',
        issuingAuthority: 'Tahasildar, Baripada',
        extractedIncome: 210000
      }
    ]
  },
  {
    id: 'IND-ST-2026-9655',
    applicantName: 'Bikram Gond',
    fatherName: 'Ghanaram Gond',
    dob: '2002-03-25',
    gender: 'Male',
    tribe: 'Gond',
    state: 'Chhattisgarh',
    district: 'Kanker',
    institution: 'Govt Bhanupratappur College Kanker',
    schemeId: 'SCH-PMSC-03',
    schemeName: 'Post-Matric Scholarship for ST Students',
    annualIncomeDeclared: 130000,
    annualIncomeExtracted: 130000,
    incomeMismatch: false,
    casteCertNo: 'CG/KNK/ST/2024/77012',
    casteVerified: true,
    aadhaarSeeded: true,
    bankAccount: '44102938102',
    bankIfsc: 'SBIN0001920',
    bankName: 'State Bank of India (Kanker)',
    aiConfidenceScore: 94,
    status: 'AUTO_VERIFIED',
    discrepancySignal: 'CG State Portal e-District Verified',
    triageFolder: 'high',
    appliedDate: '2026-08-08',
    documentList: [
      { 
        id: 'doc-100', 
        name: 'Income_Kanker.pdf', 
        hasDiscrepancy: false, 
        statusBadge: '✅ Verified', 
        type: 'INCOME',
        certNumber: 'CG/KNK/INC/2026/77012',
        issueDate: '04/03/2026',
        issuingAuthority: 'Tehsildar Kanker',
        extractedIncome: 130000
      }
    ]
  },
  {
    id: 'IND-ST-2026-9670',
    applicantName: 'Deepika Meena',
    fatherName: 'Prabhu Dayal Meena',
    dob: '2000-06-14',
    gender: 'Female',
    tribe: 'Meena',
    state: 'Rajasthan',
    district: 'Banswara',
    institution: 'Govt College Banswara',
    schemeId: 'SCH-NOS-02',
    schemeName: 'National Overseas Scholarship for ST',
    annualIncomeDeclared: 190000,
    annualIncomeExtracted: 190000,
    incomeMismatch: false,
    casteCertNo: 'RJ/BSW/ST/2025/11902',
    casteVerified: true,
    aadhaarSeeded: true,
    bankAccount: '99019283741',
    bankIfsc: 'BARB0BANSWA',
    bankName: 'Bank of Baroda (Banswara)',
    aiConfidenceScore: 91,
    status: 'AUTO_VERIFIED',
    discrepancySignal: 'Foreign University Admit Letter Validated',
    triageFolder: 'high',
    appliedDate: '2026-08-16',
    documentList: [
      { 
        id: 'doc-110', 
        name: 'Income_Banswara.pdf', 
        hasDiscrepancy: false, 
        statusBadge: '✅ Verified', 
        type: 'INCOME',
        certNumber: 'RJ/BSW/INC/2026/11902',
        issueDate: '11/02/2026',
        issuingAuthority: 'Tehsildar Banswara',
        extractedIncome: 190000
      }
    ]
  },
  {
    id: 'IND-ST-2026-9685',
    applicantName: 'Rahul Santhal',
    fatherName: 'Babulal Santhal',
    dob: '2001-10-28',
    gender: 'Male',
    tribe: 'Santhal',
    state: 'Jharkhand',
    district: 'Deoghar',
    institution: 'Deoghar College',
    schemeId: 'SCH-NFST-01',
    schemeName: 'National Fellowship for ST (NFST)',
    annualIncomeDeclared: 90000,
    annualIncomeExtracted: 320000,
    incomeMismatch: true,
    casteCertNo: 'JH/DGH/ST/2024/44102',
    casteVerified: true,
    aadhaarSeeded: true,
    bankAccount: '50192837401',
    bankIfsc: 'SBIN0000921',
    bankName: 'State Bank of India (Deoghar)',
    aiConfidenceScore: 44,
    status: 'FLAGGED',
    discrepancySignal: 'Income mismatch: OCR extracted ₹3,20,000 vs Declared ₹90,000',
    triageFolder: 'flagged',
    appliedDate: '2026-08-19',
    ocrConflictNote: 'AI OCR conflict: Extracted Tehsildar Income Certificate shows ₹3,20,000/-',
    documentList: [
      { 
        id: 'doc-120', 
        name: 'Income_Cert_Deoghar.pdf', 
        hasDiscrepancy: true, 
        statusBadge: '⚠️ Discrepancy Flagged', 
        type: 'INCOME',
        certNumber: 'JH/DGH/INC/2026/44102',
        issueDate: '08/03/2026',
        issuingAuthority: 'Sub-Divisional Magistrate, Deoghar',
        extractedIncome: 320000,
        discrepancyNote: 'Certificate states family annual income ₹3,20,000 vs applicant declaration ₹90,000'
      }
    ]
  },
  {
    id: 'IND-ST-2026-9700',
    applicantName: 'Preeti Kispotta',
    fatherName: 'Cornelius Kispotta',
    dob: '2004-01-15',
    gender: 'Female',
    tribe: 'Oraon',
    state: 'Chhattisgarh',
    district: 'Dantewada',
    institution: 'Govt Model College Dantewada',
    schemeId: 'SCH-PREM-04',
    schemeName: 'Pre-Matric ST Scholarship',
    annualIncomeDeclared: 72000,
    annualIncomeExtracted: 72000,
    incomeMismatch: false,
    casteCertNo: 'CG/DTW/ST/2025/00192',
    casteVerified: true,
    aadhaarSeeded: true,
    bankAccount: '33019283749',
    bankIfsc: 'CNRB0001890',
    bankName: 'Canara Bank (Dantewada)',
    aiConfidenceScore: 99,
    status: 'AUTO_VERIFIED',
    discrepancySignal: 'Full AI Pre-Verification Passed',
    triageFolder: 'high',
    appliedDate: '2026-08-02',
    documentList: [
      { 
        id: 'doc-130', 
        name: 'Income_Dantewada.pdf', 
        hasDiscrepancy: false, 
        statusBadge: '✅ Verified', 
        type: 'INCOME',
        certNumber: 'CG/DTW/INC/2026/00192',
        issueDate: '22/01/2026',
        issuingAuthority: 'Tehsildar Dantewada',
        extractedIncome: 72000
      }
    ]
  },
  {
    id: 'IND-ST-2026-9715',
    applicantName: 'Vijay Bodo',
    fatherName: 'Bhaben Bodo',
    dob: '2002-11-20',
    gender: 'Male',
    tribe: 'Bodo',
    state: 'Assam',
    district: 'Kokrajhar',
    institution: 'Bodoland University',
    schemeId: 'SCH-PMSC-03',
    schemeName: 'Post-Matric Scholarship for ST Students',
    annualIncomeDeclared: 115000,
    annualIncomeExtracted: 115000,
    incomeMismatch: false,
    casteCertNo: 'AS/KKR/ST/2024/88091',
    casteVerified: true,
    aadhaarSeeded: true,
    bankAccount: '60192837491',
    bankIfsc: 'UTBI0KOK301',
    bankName: 'United Bank of India (Kokrajhar)',
    aiConfidenceScore: 96,
    status: 'AUTO_VERIFIED',
    discrepancySignal: 'Assam BTC Portal Verified',
    triageFolder: 'high',
    appliedDate: '2026-08-09',
    documentList: [
      { 
        id: 'doc-140', 
        name: 'Income_Kokrajhar.pdf', 
        hasDiscrepancy: false, 
        statusBadge: '✅ Verified', 
        type: 'INCOME',
        certNumber: 'AS/KKR/INC/2026/88091',
        issueDate: '17/02/2026',
        issuingAuthority: 'Circle Officer, Kokrajhar',
        extractedIncome: 115000
      }
    ]
  },
  {
    id: 'IND-ST-2026-9730',
    applicantName: 'Mary Ningthouja',
    fatherName: 'Tomba Singh',
    dob: '2001-03-04',
    gender: 'Female',
    tribe: 'Kuki',
    state: 'Manipur',
    district: 'Churachandpur',
    institution: 'Manipur University Imphal',
    schemeId: 'SCH-NOS-02',
    schemeName: 'National Overseas Scholarship for ST',
    annualIncomeDeclared: 175000,
    annualIncomeExtracted: 175000,
    incomeMismatch: false,
    casteCertNo: 'MN/CCP/ST/2025/11092',
    casteVerified: true,
    aadhaarSeeded: true,
    bankAccount: '77102938491',
    bankIfsc: 'SBIN0001802',
    bankName: 'State Bank of India (Churachandpur)',
    aiConfidenceScore: 89,
    status: 'AUTO_VERIFIED',
    discrepancySignal: 'Manipur State e-District Verified',
    triageFolder: 'high',
    appliedDate: '2026-08-17',
    documentList: [
      { 
        id: 'doc-150', 
        name: 'Income_Churachandpur.pdf', 
        hasDiscrepancy: false, 
        statusBadge: '✅ Verified', 
        type: 'INCOME',
        certNumber: 'MN/CCP/INC/2026/11092',
        issueDate: '19/02/2026',
        issuingAuthority: 'Deputy Commissioner, Churachandpur',
        extractedIncome: 175000
      }
    ]
  },
  {
    id: 'IND-ST-2026-9745',
    applicantName: 'Manoj Khasi',
    fatherName: 'Purno Khasi',
    dob: '2000-05-18',
    gender: 'Male',
    tribe: 'Khasi',
    state: 'Meghalaya',
    district: 'East Khasi Hills',
    institution: 'North Eastern Hill University (NEHU Shillong)',
    schemeId: 'SCH-NFST-01',
    schemeName: 'National Fellowship for ST (NFST)',
    annualIncomeDeclared: 160000,
    annualIncomeExtracted: 160000,
    incomeMismatch: false,
    casteCertNo: 'ML/EKH/ST/2024/99012',
    casteVerified: true,
    aadhaarSeeded: true,
    bankAccount: '88019283749',
    bankIfsc: 'SBIN0001850',
    bankName: 'State Bank of India (NEHU Shillong)',
    aiConfidenceScore: 98,
    status: 'AUTO_VERIFIED',
    discrepancySignal: 'Meghalaya Portal Validated',
    triageFolder: 'high',
    appliedDate: '2026-08-04',
    documentList: [
      { 
        id: 'doc-160', 
        name: 'Income_Shillong.pdf', 
        hasDiscrepancy: false, 
        statusBadge: '✅ Verified', 
        type: 'INCOME',
        certNumber: 'ML/EKH/INC/2026/99012',
        issueDate: '14/03/2026',
        issuingAuthority: 'Extra Assistant Commissioner, Shillong',
        extractedIncome: 160000
      }
    ]
  },
  {
    id: 'IND-ST-2026-9760',
    applicantName: 'Bablu Munda',
    fatherName: 'Somra Munda',
    dob: '2004-08-12',
    gender: 'Male',
    tribe: 'Munda',
    state: 'Jharkhand',
    district: 'Khunti',
    institution: 'Birsa College Khunti',
    schemeId: 'SCH-PREM-04',
    schemeName: 'Pre-Matric ST Scholarship',
    annualIncomeDeclared: 95000,
    annualIncomeExtracted: 95000,
    incomeMismatch: false,
    casteCertNo: 'JH/KNT/ST/2025/33091',
    casteVerified: true,
    aadhaarSeeded: false,
    bankAccount: '11092837410',
    bankIfsc: 'PUNB0291001',
    bankName: 'Punjab National Bank (Khunti)',
    aiConfidenceScore: 76,
    status: 'NEEDS_REVIEW',
    discrepancySignal: 'Manual Income Stamp Inspection Required',
    triageFolder: 'manual',
    appliedDate: '2026-08-21',
    documentList: [
      { 
        id: 'doc-170', 
        name: 'Income_Khunti.pdf', 
        hasDiscrepancy: true, 
        statusBadge: '🟡 Manual Stamp Review', 
        type: 'INCOME',
        certNumber: 'JH/KNT/INC/2026/33091',
        issueDate: '05/02/2026',
        issuingAuthority: 'Circle Officer, Khunti',
        extractedIncome: 95000,
        discrepancyNote: 'Manual stamp verification pending from Block Office'
      }
    ]
  },
  {
    id: 'IND-ST-2026-9775',
    applicantName: 'Sunita Lambada',
    fatherName: 'Ramu Naik Lambada',
    dob: '2002-04-09',
    gender: 'Female',
    tribe: 'Lambada',
    state: 'Telangana',
    district: 'Adilabad',
    institution: 'Kakatiya University Warangal',
    schemeId: 'SCH-PMSC-03',
    schemeName: 'Post-Matric Scholarship for ST Students',
    annualIncomeDeclared: 145000,
    annualIncomeExtracted: 145000,
    incomeMismatch: false,
    casteCertNo: 'TG/ADB/ST/2024/77091',
    casteVerified: true,
    aadhaarSeeded: true,
    bankAccount: '90192837410',
    bankIfsc: 'SBIN0002100',
    bankName: 'State Bank of India (Adilabad)',
    aiConfidenceScore: 95,
    status: 'AUTO_VERIFIED',
    discrepancySignal: 'ePASS Telangana API Verified',
    triageFolder: 'high',
    appliedDate: '2026-08-07',
    documentList: [
      { 
        id: 'doc-180', 
        name: 'Income_Adilabad.pdf', 
        hasDiscrepancy: false, 
        statusBadge: '✅ Verified', 
        type: 'INCOME',
        certNumber: 'TG/ADB/INC/2026/77091',
        issueDate: '12/03/2026',
        issuingAuthority: 'Tahsildar, Adilabad Rural',
        extractedIncome: 145000
      }
    ]
  },
  {
    id: 'IND-ST-2026-9790',
    applicantName: 'Devendra Toda',
    fatherName: 'Kuttan Toda',
    dob: '2000-12-30',
    gender: 'Male',
    tribe: 'Toda',
    state: 'Tamil Nadu',
    district: 'Nilgiris',
    institution: 'Government Arts College Ooty',
    schemeId: 'SCH-NFST-01',
    schemeName: 'National Fellowship for ST (NFST)',
    annualIncomeDeclared: 155000,
    annualIncomeExtracted: 155000,
    incomeMismatch: false,
    casteCertNo: 'TN/NLG/ST/2025/11090',
    casteVerified: true,
    aadhaarSeeded: true,
    bankAccount: '44019283749',
    bankIfsc: 'IOBA0001920',
    bankName: 'Indian Overseas Bank (Ooty)',
    aiConfidenceScore: 97,
    status: 'AUTO_VERIFIED',
    discrepancySignal: 'TN e-District Validated',
    triageFolder: 'high',
    appliedDate: '2026-08-13',
    documentList: [
      { 
        id: 'doc-190', 
        name: 'Income_Nilgiris.pdf', 
        hasDiscrepancy: false, 
        statusBadge: '✅ Verified', 
        type: 'INCOME',
        certNumber: 'TN/NLG/INC/2026/11090',
        issueDate: '28/01/2026',
        issuingAuthority: 'Tahsildar, Udhagamandalam',
        extractedIncome: 155000
      }
    ]
  }
];

export const INITIAL_PFMS_BATCHES: PfmsBatch[] = [
  {
    id: 'b1',
    batchCode: 'SO-2026-OCT-092',
    schemeName: 'National Fellowship for ST (Q3 Stipends)',
    beneficiaryCount: 1420,
    totalAmountInr: '5,82,20,000',
    auditVerification: '100% Aadhaar Seeded',
    dscStatus: 'Signed (NIC Digital Token)',
    status: 'READY',
    timestamp: '2026-10-14 09:15 IST'
  },
  {
    id: 'b2',
    batchCode: 'SO-2026-OCT-093',
    schemeName: 'National Overseas ST (Tuition Remittance)',
    beneficiaryCount: 84,
    totalAmountInr: '14,28,00,000',
    auditVerification: 'RBI Forex Cleared',
    dscStatus: 'Signed (Joint Secretary MoTA)',
    status: 'READY',
    timestamp: '2026-10-14 08:30 IST'
  },
  {
    id: 'b3',
    batchCode: 'SO-2026-OCT-091',
    schemeName: 'Post-Matric Scholarship Batch #4',
    beneficiaryCount: 8900,
    totalAmountInr: '12,40,00,000',
    auditVerification: 'SNO Audit Complete',
    dscStatus: 'Cleared E-Sign',
    status: 'TRANSMITTED',
    timestamp: '2026-10-13 18:00 IST'
  }
];

export const INITIAL_PFMS_FAILURES: PfmsFailure[] = [
  {
    id: 'f1',
    beneficiaryName: 'Manoj Kumar Gond',
    accountNo: '30829100492',
    ifsc: 'SBIN0001092',
    failureReason: 'Invalid IFSC / Merged Branch Code Error',
    errorCode: 'E04 - Invalid IFSC',
    status: 'ACTION_REQUIRED',
    applicationId: 'IND-ST-2026-7712'
  },
  {
    id: 'f2',
    beneficiaryName: 'Sunita Marandi',
    accountNo: '48100293811',
    ifsc: 'PUNB0291000',
    failureReason: 'Account Dormant / Monthly Credit Limit Exceeded',
    errorCode: 'E19 - Account Inactive',
    status: 'ACTION_REQUIRED',
    applicationId: 'IND-ST-2026-8831'
  },
  {
    id: 'f3',
    beneficiaryName: 'Vikas Kispotta',
    accountNo: '91002938491',
    ifsc: 'BARB0JHAXXX',
    failureReason: 'Aadhaar Mapping Delinked at Bank NPCI Gateway',
    errorCode: 'E88 - NPCI Inactive',
    status: 'ACTION_REQUIRED',
    applicationId: 'IND-ST-2026-9901'
  }
];

export const INITIAL_GRIEVANCES: GrievanceTicket[] = [
  {
    id: 1,
    ticketCode: 'G-882',
    applicantName: 'Rahul Gond',
    schemeName: 'National Fellowship for ST (NFST)',
    regNo: 'NFST-2025-1049',
    email: 'rahul.gond@univ-bastar.ac.in',
    mobile: '+91 94251XXXXX',
    district: 'Bastar',
    state: 'Chhattisgarh',
    subject: 'Scholarship stipend not credited for Q2',
    message: 'Respected Sir, I am an NFST research scholar at Bastar University. My quarterly fellowship for July-September 2026 has not been disbursed to my SBI account. The portal shows status "Scrutiny Pending at SNO Level" for the past 45 days. My HOD has already forwarded the physical attendance certificate. Kindly release the stipend at the earliest.',
    aiSuggestedDraft: 'Dear Applicant, your representation regarding stipend release under National Fellowship for ST (NFST) has been examined. Your continuation certificate and quarterly progress report are currently under scrutiny at the State Nodal Officer (SNO) level for Bastar district. As per scheme guidelines, PFMS DBT transmission occurs following bi-monthly clearance. Kindly wait for 15 working days. You can track docket clearance using reference MOTA/FELL/2026/Q3.',
    status: 'OPEN',
    timestamp: '2 hours ago'
  },
  {
    id: 2,
    ticketCode: 'G-883',
    applicantName: 'Pooja Bhagat',
    schemeName: 'Post-Matric ST Scholarship',
    regNo: 'PMS-ST-2026-4401',
    email: 'pooja.bhagat@gmail.com',
    mobile: '+91 98352XXXXX',
    district: 'Ranchi',
    state: 'Jharkhand',
    subject: 'Income certificate defect marked erroneously',
    message: 'Respected Officer, the SNO marked defect on my certificate citing illegible stamp. I have uploaded the digital e-signed certificate with QR code issued by JharSewa. Please verify online directly.',
    aiSuggestedDraft: 'Dear Applicant, your complaint regarding income certificate verification has been reviewed. The digital QR-coded certificate issued by JharSewa (Token JH/RNC/2026) has been re-validated via e-District API. The defect status has been removed and your application is now queued for batch sanction.',
    status: 'OPEN',
    timestamp: '5 hours ago'
  },
  {
    id: 3,
    ticketCode: 'G-884',
    applicantName: 'Amit Tirkey',
    schemeName: 'Pre-Matric ST Scholarship',
    regNo: 'PREM-2026-9901',
    email: 'tirkey.family@yahoo.in',
    mobile: '+91 94371XXXXX',
    district: 'Sundargarh',
    state: 'Odisha',
    subject: 'Institute nodal officer not approving application',
    message: 'Sir, the nodal officer in our school has been on leave. Deadline is approaching on 31st October. Please direct district inspector to approve pending school verification.',
    aiSuggestedDraft: 'Dear Applicant, your representation has been forwarded to the District Welfare Officer (DWO), Sundargarh district with instructions to initiate administrative override for institutional verification before the portal deadline.',
    status: 'OPEN',
    timestamp: '1 day ago'
  }
];
